---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/destinations":
    post:
      summary: Creates a destination
      tags:
      - Destinations
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: destination
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            country:
              type: string
            city:
              type: string
          required:
          - name
          - country
          - city
      responses:
        '201':
          description: destination created
        '422':
          description: invalid request
  "/destinations/{id}":
    get:
      summary: Retrieves a destination
      tags:
      - Destinations
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              country:
                type: string
              city:
                type: string
            required:
            - id
            - name
            - country
            - city
        '404':
          description: destination not found
